default_stages: [commit, push]
fail_fast: true
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
        - flake8-docstrings
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-builtins
        - flake8-return
