default_stages: [commit, push]
fail_fast: true
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.0
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 21.10b0
    hooks:
      - id: black
  - repo: https://gitlab.com/PyCQA/flake8
    rev: '3.8.3'
    hooks:
      - id: flake8
        additional_dependencies:
        - flake8-docstrings
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-builtins
        - flake8-return
