version: "3"
services:
  s3:
    ports:
    - "9000:9000"
    image: minio/minio
    command:
    - server
    - /data
    environment:
      MINIO_ACCESS_KEY: pathlibfs
      MINIO_SECRET_KEY: pathlibfs