name: check

on:
  push:
    branches:
    - main
  pull_request:
    # branches:
    # - '!releases/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: flake8 --all-files
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: curl -sSL https://install.python-poetry.org | python3 -
    - name: Start services for unittest
      run: docker-compose up -d
    - run: poetry install
    - run: poetry run pytest -vv --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
